// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $game from "./routes/game.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $gummy_list from "./routes/gummy-list.tsx";
import * as $index from "./routes/index.tsx";
import * as $sns from "./routes/sns.tsx";
import * as $user from "./routes/user.tsx";
import * as $Calorie from "./islands/Calorie.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Footer from "./islands/Footer.tsx";
import * as $GummyList from "./islands/GummyList.tsx";
import * as $GummyOpen from "./islands/GummyOpen.tsx";
import * as $PostList from "./islands/PostList.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/game.tsx": $game,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/gummy-list.tsx": $gummy_list,
    "./routes/index.tsx": $index,
    "./routes/sns.tsx": $sns,
    "./routes/user.tsx": $user,
  },
  islands: {
    "./islands/Calorie.tsx": $Calorie,
    "./islands/Counter.tsx": $Counter,
    "./islands/Footer.tsx": $Footer,
    "./islands/GummyList.tsx": $GummyList,
    "./islands/GummyOpen.tsx": $GummyOpen,
    "./islands/PostList.tsx": $PostList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
